# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project_one.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1540, 800)
        MainWindow.setStyleSheet("background-color: rgb(181, 181, 181);\n"
"background-color: rgb(199, 199, 199);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 1500, 700))
        self.layoutWidget.setObjectName("layoutWidget")
        self.Main_layout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.Main_layout.setContentsMargins(0, 0, 0, 0)
        self.Main_layout.setObjectName("Main_layout")
        self.Layout2 = QtWidgets.QHBoxLayout()
        self.Layout2.setObjectName("Layout2")
        self.Layout1 = QtWidgets.QVBoxLayout()
        self.Layout1.setObjectName("Layout1")
        self.exersise = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.exersise.setFont(font)
        self.exersise.setStyleSheet("color: rgb(50, 18, 158);")
        self.exersise.setObjectName("exersise")
        self.Layout1.addWidget(self.exersise)
        #self.text = QtWidgets.QCheckBox(self.layoutWidget)
        self.text1 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.text1.setFont(font)
        self.text1.setStyleSheet("\n"
"background-color: rgb(255, 162, 85);")
        self.text1.setText('text')
        #self.text.setObjectName("text")
        #self.text.toggle()
        #self.text.stateChanged.connect(self.Exersize)
        self.Layout1.addWidget(self.text1)
        self.symbol = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.symbol.setFont(font)
        self.symbol.setStyleSheet("\n"
"background-color: rgb(255, 162, 85);")
        self.symbol.setObjectName("symbol")
        #self.symbol.toggle()
        #self.symbol.stateChanged.connect(self.Exersize)
        self.Layout1.addWidget(self.symbol)

        self.go = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.go.setFont(font)
        self.go.setStyleSheet("color: rgb(3, 3, 3);\n"
"background-color: rgb(255, 162, 85);")
        self.go.setObjectName("go")
        self.go.setText("Получить задание")
        self.Layout1.addWidget(self.go)
        self.Layout2.addLayout(self.Layout1)
        self.test = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.test.setFont(font)
        self.test.setStyleSheet("color: rgb(50, 18, 158);")
        self.test.setObjectName("test")
        self.Layout2.addWidget(self.test)
        self.testplace = QtWidgets.QTextBrowser(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.testplace.setFont(font)
        self.testplace.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.testplace.setObjectName("testplace")
        self.Layout2.addWidget(self.testplace)
        self.restart = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.restart.setFont(font)
        self.restart.setStyleSheet("color: rgb(3, 3, 3);\n"
"background-color: rgb(255, 162, 85);")
        self.restart.setObjectName("restart")
        self.Layout2.addWidget(self.restart)
        self.Main_layout.addLayout(self.Layout2)
        self.Layout4 = QtWidgets.QHBoxLayout()
        self.Layout4.setObjectName("Layout4")
        self.answer = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.answer.setFont(font)
        self.answer.setStyleSheet("color: rgb(50, 18, 158);")
        self.answer.setObjectName("answer")
        self.Layout4.addWidget(self.answer)
        self.answershit = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.answershit.setFont(font)
        self.answershit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.answershit.setObjectName("answershit")
        self.Layout4.addWidget(self.answershit)
        self.Layout3 = QtWidgets.QVBoxLayout()
        self.Layout3.setObjectName("Layout3")
        self.language = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.language.setFont(font)
        self.language.setStyleSheet("color: rgb(50, 18, 158);")
        self.language.setObjectName("language")
        self.Layout3.addWidget(self.language)
        self.RU = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.RU.setFont(font)
        self.RU.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 162, 85);\n"
"")
        self.RU.setObjectName("RU")
        #self.RU.toggled.connect(lambda:self.btnstate(self.RU))
        self.RU.setChecked(True)
        self.Layout3.addWidget(self.RU)
        self.EN = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EN.setFont(font)
        self.EN.setStyleSheet("background-color: rgb(255, 162, 85);\n"
"")
        self.EN.setObjectName("EN")
        #self.EN.toggled.connect(lambda:self.btnstate(self.EN))
        self.Layout3.addWidget(self.EN)
        self.button_group = QtWidgets.QButtonGroup()
        self.button_group.addButton(self.RU)
        self.button_group.addButton(self.EN)
        #self.Layout3.addWidget(self.button_group)
        self.Layout4.addLayout(self.Layout3)
        self.Main_layout.addLayout(self.Layout4)
        self.result = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.result.setFont(font)
        self.result.setStyleSheet("color: rgb(50, 18, 158);")
        self.result.setObjectName("result")
        self.Main_layout.addWidget(self.result)
        self.Layout_k = QtWidgets.QVBoxLayout()
        self.Layout_k.setObjectName("Layout_k")
        self.k1 = QtWidgets.QHBoxLayout()
        self.k1.setObjectName("k1")
        self.btn_io = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_io.setFont(font)
        self.btn_io.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.btn_io.setObjectName("btn_io")
        self.k1.addWidget(self.btn_io)
        self.btn_1 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_1.setFont(font)
        self.btn_1.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"background-color: rgb(0, 170, 255);")
        self.btn_1.setObjectName("btn_1")
        self.k1.addWidget(self.btn_1)
        self.btn_2 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_2.setFont(font)
        self.btn_2.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.btn_2.setObjectName("btn_2")
        self.k1.addWidget(self.btn_2)
        self.btn_3 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_3.setFont(font)
        self.btn_3.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.btn_3.setObjectName("btn_3")
        self.k1.addWidget(self.btn_3)
        self.btn_4 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_4.setFont(font)
        self.btn_4.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.btn_4.setObjectName("btn_4")
        self.k1.addWidget(self.btn_4)
        self.btn_5 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_5.setFont(font)
        self.btn_5.setStyleSheet("background-color: rgb(253, 116, 141);")
        self.btn_5.setObjectName("btn_5")
        self.k1.addWidget(self.btn_5)
        self.btn_6 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_6.setFont(font)
        self.btn_6.setStyleSheet("background-color: rgb(253, 116, 141);")
        self.btn_6.setObjectName("btn_6")
        self.k1.addWidget(self.btn_6)
        self.btn_7 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_7.setFont(font)
        self.btn_7.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.btn_7.setObjectName("btn_7")
        self.k1.addWidget(self.btn_7)
        self.btn_8 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_8.setFont(font)
        self.btn_8.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.btn_8.setObjectName("btn_8")
        self.k1.addWidget(self.btn_8)
        self.btn_9 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_9.setFont(font)
        self.btn_9.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"background-color: rgb(170, 255, 127);")
        self.btn_9.setObjectName("btn_9")
        self.k1.addWidget(self.btn_9)
        self.btn_0 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_0.setFont(font)
        self.btn_0.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"background-color: rgb(0, 170, 255);")
        self.btn_0.setObjectName("btn_0")
        self.k1.addWidget(self.btn_0)
        self.btn_minus = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_minus.setFont(font)
        self.btn_minus.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.btn_minus.setObjectName("btn_minus")
        self.k1.addWidget(self.btn_minus)
        self.btn_plus = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_plus.setFont(font)
        self.btn_plus.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.btn_plus.setObjectName("btn_plus")
        self.k1.addWidget(self.btn_plus)
        self.btn_backspace = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_backspace.setFont(font)
        self.btn_backspace.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"")
        self.btn_backspace.setObjectName("btn_backspace")
        self.k1.addWidget(self.btn_backspace)
        self.Layout_k.addLayout(self.k1)
        self.k2 = QtWidgets.QHBoxLayout()
        self.k2.setObjectName("k2")
        self.btn_q = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_q.setFont(font)
        self.btn_q.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.btn_q.setObjectName("btn_q")
        self.k2.addWidget(self.btn_q)
        self.btn_w = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_w.setFont(font)
        self.btn_w.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"background-color: rgb(0, 170, 255);")
        self.btn_w.setObjectName("btn_w")
        self.k2.addWidget(self.btn_w)
        self.btn_e = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_e.setFont(font)
        self.btn_e.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.btn_e.setObjectName("btn_e")
        self.k2.addWidget(self.btn_e)
        self.btn_r = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_r.setFont(font)
        self.btn_r.setStyleSheet("background-color: rgb(253, 116, 141);")
        self.btn_r.setObjectName("btn_r")
        self.k2.addWidget(self.btn_r)
        self.btn_t = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_t.setFont(font)
        self.btn_t.setStyleSheet("background-color: rgb(253, 116, 141);")
        self.btn_t.setObjectName("btn_t")
        self.k2.addWidget(self.btn_t)
        self.btn_y = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_y.setFont(font)
        self.btn_y.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.btn_y.setObjectName("btn_y")
        self.k2.addWidget(self.btn_y)
        self.btn_u = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_u.setFont(font)
        self.btn_u.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.btn_u.setObjectName("btn_u")
        self.k2.addWidget(self.btn_u)
        self.btn_i = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_i.setFont(font)
        self.btn_i.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.btn_i.setObjectName("btn_i")
        self.k2.addWidget(self.btn_i)
        self.btn_o = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_o.setFont(font)
        self.btn_o.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.btn_o.setObjectName("btn_o")
        self.k2.addWidget(self.btn_o)
        self.btn_p = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_p.setFont(font)
        self.btn_p.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.btn_p.setObjectName("btn_p")
        self.k2.addWidget(self.btn_p)
        self.btn_xa = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_xa.setFont(font)
        self.btn_xa.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.btn_xa.setObjectName("btn_xa")
        self.k2.addWidget(self.btn_xa)
        self.btn_tv_zn = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_tv_zn.setFont(font)
        self.btn_tv_zn.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.btn_tv_zn.setObjectName("btn_tv_zn")
        self.k2.addWidget(self.btn_tv_zn)
        self.Layout_k.addLayout(self.k2)
        self.k3 = QtWidgets.QHBoxLayout()
        self.k3.setObjectName("k3")
        self.btn_capslock = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_capslock.setFont(font)
        self.btn_capslock.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.btn_capslock.setObjectName("btn_capslock")
        self.k3.addWidget(self.btn_capslock)
        self.btn_a = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_a.setFont(font)
        self.btn_a.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.btn_a.setObjectName("btn_a")
        self.k3.addWidget(self.btn_a)
        self.btn_s = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_s.setFont(font)
        self.btn_s.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.btn_s.setObjectName("btn_s")
        self.k3.addWidget(self.btn_s)
        self.btn_d = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_d.setFont(font)
        self.btn_d.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.btn_d.setObjectName("btn_d")
        self.k3.addWidget(self.btn_d)
        self.btn_f = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_f.setFont(font)
        self.btn_f.setStyleSheet("background-color: rgb(253, 116, 141);")
        self.btn_f.setObjectName("btn_f")
        self.k3.addWidget(self.btn_f)
        self.btn_g = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_g.setFont(font)
        self.btn_g.setStyleSheet("background-color: rgb(253, 116, 141);")
        self.btn_g.setObjectName("btn_g")
        self.k3.addWidget(self.btn_g)
        self.btn_h = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_h.setFont(font)
        self.btn_h.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.btn_h.setObjectName("btn_h")
        self.k3.addWidget(self.btn_h)
        self.btn_j = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_j.setFont(font)
        self.btn_j.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.btn_j.setObjectName("btn_j")
        self.k3.addWidget(self.btn_j)
        self.btn_k = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_k.setFont(font)
        self.btn_k.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.btn_k.setObjectName("btn_k")
        self.k3.addWidget(self.btn_k)
        self.btn_l = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_l.setFont(font)
        self.btn_l.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"background-color: rgb(0, 170, 255);")
        self.btn_l.setObjectName("btn_l")
        self.k3.addWidget(self.btn_l)
        self.btn_gh = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_gh.setFont(font)
        self.btn_gh.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"background-color: rgb(255, 255, 127);")
        self.btn_gh.setObjectName("btn_gh")
        self.k3.addWidget(self.btn_gh)
        self.btn_ei = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_ei.setFont(font)
        self.btn_ei.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.btn_ei.setObjectName("btn_ei")
        self.k3.addWidget(self.btn_ei)
        '''self.btn_slash = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_slash.setFont(font)
        self.btn_slash.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.btn_slash.setObjectName("btn_slash")
        self.k3.addWidget(self.btn_slash)'''
        self.btn_enter = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_enter.setFont(font)
        self.btn_enter.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.btn_enter.setObjectName("btn_enter")
        self.k3.addWidget(self.btn_enter)
        self.Layout_k.addLayout(self.k3)
        self.k4 = QtWidgets.QHBoxLayout()
        self.k4.setObjectName("k4")
        self.btn_shift = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_shift.setFont(font)
        self.btn_shift.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.btn_shift.setObjectName("btn_shift")
        self.k4.addWidget(self.btn_shift)
        self.btn_z = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_z.setFont(font)
        self.btn_z.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"background-color: rgb(0, 170, 255);")
        self.btn_z.setObjectName("btn_z")
        self.k4.addWidget(self.btn_z)
        self.btn_x = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_x.setFont(font)
        self.btn_x.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.btn_x.setObjectName("btn_x")
        self.k4.addWidget(self.btn_x)
        self.btn_c = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_c.setFont(font)
        self.btn_c.setStyleSheet("background-color: rgb(253, 116, 141);")
        self.btn_c.setObjectName("btn_c")
        self.k4.addWidget(self.btn_c)
        self.btn_v = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_v.setFont(font)
        self.btn_v.setStyleSheet("background-color: rgb(253, 116, 141);")
        self.btn_v.setObjectName("btn_v")
        self.k4.addWidget(self.btn_v)
        self.btn_b = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_b.setFont(font)
        self.btn_b.setStyleSheet("background-color: rgb(253, 116, 141);")
        self.btn_b.setObjectName("btn_b")
        self.k4.addWidget(self.btn_b)
        self.btn_n = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_n.setFont(font)
        self.btn_n.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.btn_n.setObjectName("btn_n")
        self.k4.addWidget(self.btn_n)
        self.btn_m = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_m.setFont(font)
        self.btn_m.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.btn_m.setObjectName("btn_m")
        self.k4.addWidget(self.btn_m)
        self.btn_be = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_be.setFont(font)
        self.btn_be.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.btn_be.setObjectName("btn_be")
        self.k4.addWidget(self.btn_be)
        self.btn_iu = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_iu.setFont(font)
        self.btn_iu.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.btn_iu.setObjectName("btn_iu")
        self.k4.addWidget(self.btn_iu)
        self.btn_dot = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_dot.setFont(font)
        self.btn_dot.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.btn_dot.setObjectName("btn_dot")
        self.k4.addWidget(self.btn_dot)
        self.Layout_k.addLayout(self.k4)
        self.k5 = QtWidgets.QHBoxLayout()
        self.k5.setObjectName("k5")
        self.btn_ctrl = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_ctrl.setFont(font)
        self.btn_ctrl.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.btn_ctrl.setObjectName("btn_ctrl")
        self.k5.addWidget(self.btn_ctrl)
        self.btn_alt = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_alt.setFont(font)
        self.btn_alt.setStyleSheet("background-color: rgb(184, 184, 184);")
        self.btn_alt.setObjectName("btn_alt")
        self.k5.addWidget(self.btn_alt, 0, QtCore.Qt.AlignLeft)
        spacerItem = QtWidgets.QSpacerItem(298, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.k5.addItem(spacerItem)
        self.btn_space = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_space.setFont(font)
        self.btn_space.setStyleSheet("background-color: rgb(85, 170, 127);")
        self.btn_space.setObjectName("btn_space")
        self.k5.addWidget(self.btn_space)
        spacerItem1 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.k5.addItem(spacerItem1)
        self.Layout_k.addLayout(self.k5)
        self.Main_layout.addLayout(self.Layout_k)
        self.check = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.check.setFont(font)
        self.check.setStyleSheet("color: rgb(0, 0, 127);\n"
"background-color: rgb(255, 162, 85);")
        self.check.setObjectName("check")
        self.Main_layout.addWidget(self.check)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1375, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.exersise.setText(_translate("MainWindow", "Выберите задание:"))
        self.text1.setText(_translate("MainWindow", "Текст"))
        self.symbol.setText(_translate("MainWindow", "Символы"))
        self.test.setText(_translate("MainWindow", "Задание:"))
        self.testplace.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.restart.setText(_translate("MainWindow", "Начать заново"))
        self.answer.setText(_translate("MainWindow", "Ваш ответ:"))
        self.answershit.setText(_translate("MainWindow", "                                                                                                                                                                                                                                                                                                           "))
        self.language.setText(_translate("MainWindow", "Язык:"))
        self.RU.setText(_translate("MainWindow", "RU"))
        self.EN.setText(_translate("MainWindow", "EN"))
        self.result.setText(_translate("MainWindow", "Результат: ?"))
        self.btn_io.setText(_translate("MainWindow", "ё"))
        self.btn_1.setText(_translate("MainWindow", "1  !"))
        self.btn_2.setText(_translate("MainWindow", "2  \""))
        self.btn_3.setText(_translate("MainWindow", "3 №"))
        self.btn_4.setText(_translate("MainWindow", "4 ;"))
        self.btn_5.setText(_translate("MainWindow", "5 %"))
        self.btn_6.setText(_translate("MainWindow", "6  :"))
        self.btn_7.setText(_translate("MainWindow", "7 ? &"))
        self.btn_8.setText(_translate("MainWindow", "8 *"))
        self.btn_9.setText(_translate("MainWindow", "9 ("))
        self.btn_0.setText(_translate("MainWindow", "0 )"))
        self.btn_minus.setText(_translate("MainWindow", "- _"))
        self.btn_plus.setText(_translate("MainWindow", "= + "))
        self.btn_backspace.setText(_translate("MainWindow", "<- Backspace"))
        self.btn_q.setText(_translate("MainWindow", "й"))
        self.btn_w.setText(_translate("MainWindow", "ц"))
        self.btn_e.setText(_translate("MainWindow", "у"))
        self.btn_r.setText(_translate("MainWindow", "к"))
        self.btn_t.setText(_translate("MainWindow", "е"))
        self.btn_y.setText(_translate("MainWindow", "н"))
        self.btn_u.setText(_translate("MainWindow", "г"))
        self.btn_i.setText(_translate("MainWindow", "ш"))
        self.btn_o.setText(_translate("MainWindow", "щ"))
        self.btn_p.setText(_translate("MainWindow", "з"))
        self.btn_xa.setText(_translate("MainWindow", "х"))
        self.btn_tv_zn.setText(_translate("MainWindow", "ъ"))
        self.btn_capslock.setText(_translate("MainWindow", "Caps Lock"))
        self.btn_a.setText(_translate("MainWindow", "ф"))
        self.btn_s.setText(_translate("MainWindow", "ы"))
        self.btn_d.setText(_translate("MainWindow", "в"))
        self.btn_f.setText(_translate("MainWindow", "а"))
        self.btn_g.setText(_translate("MainWindow", "п"))
        self.btn_h.setText(_translate("MainWindow", "р"))
        self.btn_j.setText(_translate("MainWindow", "о"))
        self.btn_k.setText(_translate("MainWindow", "л"))
        self.btn_l.setText(_translate("MainWindow", "д"))
        self.btn_gh.setText(_translate("MainWindow", "ж"))
        self.btn_ei.setText(_translate("MainWindow", "э"))
        #self.btn_slash.setText(_translate("MainWindow", "\\ /"))
        self.btn_enter.setText(_translate("MainWindow", "Enter"))
        self.btn_shift.setText(_translate("MainWindow", "Shift"))
        self.btn_z.setText(_translate("MainWindow", "я"))
        self.btn_x.setText(_translate("MainWindow", "ч"))
        self.btn_c.setText(_translate("MainWindow", "с"))
        self.btn_v.setText(_translate("MainWindow", "м"))
        self.btn_b.setText(_translate("MainWindow", "и"))
        self.btn_n.setText(_translate("MainWindow", "т"))
        self.btn_m.setText(_translate("MainWindow", "ь"))
        self.btn_be.setText(_translate("MainWindow", "б"))
        self.btn_iu.setText(_translate("MainWindow", "ю"))
        self.btn_dot.setText(_translate("MainWindow", ". ,"))
        self.btn_ctrl.setText(_translate("MainWindow", "Ctrl"))
        self.btn_alt.setText(_translate("MainWindow", "Alt"))
        self.btn_space.setText(_translate("MainWindow", "                                                      "))
        self.check.setText(_translate("MainWindow", "Отправить на проверку"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

